[package]
edition = "2021"
name = "bfirs-bin"
version = "0.1.0"

[[bin]]
name = "bfirs"
path = "src/main.rs"

[dependencies]
anyhow = "1"
argh = "0.1"
bfirs = { path = "../lib", features = ["limited"] }
strum = "0.24"
strum_macros = "0.24"
